#include "engine/framework/assets/embedded.h"
#include "engine/framework/assets/embedded_detail.h"

#include <atomic>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <mutex>
#include <string>
#include <unordered_map>

#if defined(_WIN32)
#  include <windows.h>
#else
#  include <unistd.h>
#endif

namespace engine::assets::embedded {

// Embedded assets are active when EITHER the VAD or the audio-utilities embed
// option is on. Both produce entries in the same generated table(s); this TU
// just looks them up by id.
#if (defined(AUDIOCPP_EMBED_VAD_ASSETS) && (AUDIOCPP_EMBED_VAD_ASSETS != 0)) \
    || (defined(AUDIOCPP_EMBED_AUDIO_UTILITIES) && (AUDIOCPP_EMBED_AUDIO_UTILITIES != 0))

// Tables generated by tools/embed_asset.py at build time. Each generated file
// defines its own <prefix>_embedded_asset_table() (one per embed option) so the
// two can link together without duplicate symbols. The EmbeddedAssetEntry struct
// and these extern decls come from embedded_detail.h (single source of truth).
#if defined(AUDIOCPP_EMBED_VAD_ASSETS) && (AUDIOCPP_EMBED_VAD_ASSETS != 0)
extern const EmbeddedAssetEntry * vad_embedded_asset_table(unsigned long long * count);
#endif
#if defined(AUDIOCPP_EMBED_AUDIO_UTILITIES) && (AUDIOCPP_EMBED_AUDIO_UTILITIES != 0)
extern const EmbeddedAssetEntry * aud_embedded_asset_table(unsigned long long * count);
#endif

namespace {

const EmbeddedAssetEntry * find_entry(std::string_view id) {
    unsigned long long count = 0;
#if defined(AUDIOCPP_EMBED_VAD_ASSETS) && (AUDIOCPP_EMBED_VAD_ASSETS != 0)
    {
        const EmbeddedAssetEntry * table = vad_embedded_asset_table(&count);
        for (unsigned long long i = 0; i < count; ++i) {
            if (id == table[i].id) {
                return &table[i];
            }
        }
    }
#endif
#if defined(AUDIOCPP_EMBED_AUDIO_UTILITIES) && (AUDIOCPP_EMBED_AUDIO_UTILITIES != 0)
    {
        const EmbeddedAssetEntry * table = aud_embedded_asset_table(&count);
        for (unsigned long long i = 0; i < count; ++i) {
            if (id == table[i].id) {
                return &table[i];
            }
        }
    }
#endif
    (void)count;
    return nullptr;
}

// Per-process cache directory + materialized-file map. The directory is created
// once under the system temp root; files are written once and reused.
std::filesystem::path ensure_cache_dir() {
    static std::once_flag flag;
    static std::filesystem::path dir;
    std::call_once(flag, [] {
#if defined(_WIN32)
        char buf[MAX_PATH];
        const DWORD len = GetTempPathA(MAX_PATH, buf);
        const std::string base = (len > 0 && len < MAX_PATH) ? std::string(buf, len) : std::string(".");
#else
        const char * tmp = std::getenv("TMPDIR");
        const std::string base = (tmp != nullptr && tmp[0] != '\0') ? std::string(tmp) : std::string("/tmp");
#endif
        dir = std::filesystem::path(base) / ("audiocpp-embedded-" + std::to_string(
#ifdef _WIN32
            static_cast<long long>(GetCurrentProcessId())
#else
            static_cast<long long>(getpid())
#endif
        ));
        std::error_code ec;
        std::filesystem::create_directories(dir, ec);
    });
    return dir;
}
}  // namespace

bool has_embedded_asset(std::string_view id) {
    return find_entry(id) != nullptr;
}

const std::byte * embedded_asset_data(std::string_view id, std::size_t * out_size) {
    const auto * entry = find_entry(id);
    if (entry == nullptr) {
        return nullptr;
    }
    if (out_size != nullptr) {
        *out_size = static_cast<std::size_t>(entry->size);
    }
    return reinterpret_cast<const std::byte *>(entry->data);
}

const std::filesystem::path embedded_asset_file(std::string_view id, std::string_view dest_filename) {
    const auto * entry = find_entry(id);
    if (entry == nullptr) {
        return {};
    }
    static std::mutex map_mutex;
    static std::unordered_map<std::string, std::filesystem::path> materialized;
    const std::string key(id);
    {
        std::lock_guard<std::mutex> lock(map_mutex);
        auto it = materialized.find(key);
        std::error_code exists_ec;
        if (it != materialized.end() && std::filesystem::exists(it->second, exists_ec)) {
            return it->second;
        }
    }
    const auto dir = ensure_cache_dir();
    auto path = dir / std::string(dest_filename);
    // Write to a unique temp name (pid + counter) so concurrent first-loads of
    // the same asset don't collide on the same .tmp file, then atomically rename.
    static std::atomic<unsigned long long> counter{0};
    auto tmp = path;
    tmp += "." + std::to_string(
#ifdef _WIN32
        static_cast<long long>(GetCurrentProcessId())
#else
        static_cast<long long>(getpid())
#endif
    ) + "." + std::to_string(counter.fetch_add(1));
    {
        std::ofstream out(tmp, std::ios::binary | std::ios::trunc);
        if (!out) {
            return {};
        }
        out.write(reinterpret_cast<const char *>(entry->data), static_cast<std::streamsize>(entry->size));
        if (!out) {
            return {};
        }
    }
    std::error_code ec;
    std::filesystem::rename(tmp, path, ec);
    if (ec) {
        // rename may fail across volumes / if target exists on some platforms;
        // fall back to a direct copy.
        std::filesystem::copy_file(tmp, path, std::filesystem::copy_options::overwrite_existing, ec);
        std::error_code rm_ec;
        std::filesystem::remove(tmp, rm_ec);
    }
    {
        std::lock_guard<std::mutex> lock(map_mutex);
        materialized[key] = path;
    }
    return path;
}

#else  // no embedded assets in this build

bool has_embedded_asset(std::string_view) {
    return false;
}

const std::byte * embedded_asset_data(std::string_view, std::size_t *) {
    return nullptr;
}

const std::filesystem::path embedded_asset_file(std::string_view, std::string_view) {
    return {};
}

#endif

}  // namespace engine::assets::embedded
