#!/usr/bin/env python3
"""Generate a C++ source file embedding one or more binary assets as byte arrays.

Used by AUDIOCPP_EMBED_VAD_ASSETS so VAD models ship inside the binary with no
external file dependency. Output is a .cpp with one extern const array per
asset plus an accessor.

Usage: embed_asset.py <output.cpp> <symbol_prefix> <asset_id>:<path> [<asset_id>:<path> ...]
"""
import sys
import os
from pathlib import Path


def emit_array(out, symbol: str, data: bytes) -> None:
    out.write(f"extern const unsigned char {symbol}_data[] = {{\n")
    chunk = 12
    for i in range(0, len(data), chunk):
        line = ", ".join(f"0x{b:02x}" for b in data[i:i + chunk])
        out.write(f"    {line},\n")
    out.write("};\n")
    out.write(f"extern const unsigned long long {symbol}_size = {len(data)}ULL;\n\n")


def main() -> int:
    if len(sys.argv) < 4:
        sys.stderr.write(
            "usage: embed_asset.py <output.cpp> <symbol_prefix> "
            "<id>:<path> [<id>:<path> ...]\n")
        return 1
    output = Path(sys.argv[1])
    prefix = sys.argv[2]
    entries = []
    for arg in sys.argv[3:]:
        if ":" not in arg:
            sys.stderr.write(f"bad entry (expected id:path): {arg}\n")
            return 1
        asset_id, path = arg.split(":", 1)
        entries.append((asset_id, Path(path)))

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// AUTO-GENERATED by tools/embed_asset.py — do not edit.\n")
        out.write("// Embedded binary assets for AUDIOCPP_EMBED_*.\n")
        out.write('#include "engine/framework/assets/embedded_detail.h"\n\n')
        out.write(f"namespace engine::assets::embedded {{\n\n")
        index_entries = []
        for asset_id, path in entries:
            data = path.read_bytes()
            symbol = f"{prefix}_{asset_id}"
            emit_array(out, symbol, data)
            index_entries.append((asset_id, symbol))
        # The table function is named per-prefix so multiple generated files
        # (VAD + audio-utilities) can link together without a duplicate symbol.
        # EmbeddedAssetEntry struct comes from embedded_detail.h (single source).
        out.write(f"const EmbeddedAssetEntry * {prefix}_embedded_asset_table(unsigned long long * count) {{\n")
        out.write(f"    static const EmbeddedAssetEntry table[] = {{\n")
        for asset_id, symbol in index_entries:
            out.write(f'        {{"{asset_id}", {symbol}_data, {symbol}_size}},\n')
        out.write("    };\n")
        out.write("    *count = sizeof(table) / sizeof(table[0]);\n")
        out.write("    return table;\n")
        out.write("}\n\n")
        out.write("}  // namespace engine::assets::embedded\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
